name: Deploy static content to Pages

on:
  push:
    branches: ["main"]  # or "master" if you're using master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # root folder of your HTML/CSS files

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
